### ISSUE TITLE
Information for the relatedEntities are missing.

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/senzing-api-server#150] opened 2020-04-16 06:09 UTC
Hi Team,

We are using this (**/entity-networks**) API (Ref: http://editor.swagger.io/?url=https://raw.githubusercontent.com/Senzing/senzing-rest-api/master/senzing-rest-api.yaml) to retrieve data from the database to reflect the data in our graph.

We are getting data for the resolveEntity and relatedEntities from the API, but the basic information inside the relatedEntities are empty.

![1](https://user-images.githubusercontent.com/48215082/79420576-cf8bdc80-7fd6-11ea-93c3-3d10c23b1285.png)

Can we have the relevant information for all the attribute in the relatedEntities array?

Do we have anyother APIs to get those information?

Kindly help us to resolve these issues.

Thanks.

**Comment by barrycaceres** [comment] 2020-04-16 17:34
This appears to be duplicate of issue #147  .  Can this be closed?

**Comment by SaravananKalimuthu21** [comment] 2020-04-17 06:18
**NOTE: if we were to fully populate every "related entity" we return you could end up with megabytes of redundant JSON for highly related entities. That is why the full information is kept at the "resolved entity" and should be looked up. We fudge this for a single entity retrieval if withRelated=true since we are not going to end up multiplying the response size exponentially for only a single entity. This is why SzRelatedEntity.partial property exists -- to tell you when the data is partial and you have to either lookup the additional info from the SzResolvedEntity or do another GET operation to retrieve it.**

Is the above mentioned stanza the answer for #150?

**Comment by SaravananKalimuthu21** [comment] 2020-04-17 09:37
Hi Barry,

We don't see any relatedEntities information inside the resolvedEntity.

![API_response](https://user-images.githubusercontent.com/48215082/79555335-06d4b900-80bd-11ea-90f7-dab846d89771.png)

So what you are saying is, In order to get the details of records inside the relatedEntities{} we have to loop through it and make separate api calls with its entityId right?

**Comment by barrycaceres** [comment] 2020-04-17 18:28
Yes -- that stanza does answer #150 -- you can increase the number of entities for which you get "RESOLVED_ENTITY" values back using `maxDegrees` and `buildOut`, but the related sections are always partial for those.  They are ONLY populated if you call `GET /entities/{entityId}?withRelated=true` or `GET /data-sources/{dataSourceCode}/records/{recordId}/entity?withRelated=true`

**Comment by SaravananKalimuthu21** [comment] 2020-04-27 06:31
Hi Barry, 

When can we join together for a call?

**Comment by barrycaceres** [comment] 2020-05-14 17:03
This was explained and the usage for getting full entity information was provided on the call.  Closing.

**Closed by barrycaceres** 2020-05-14 17:03 UTC
