### ISSUE TITLE
GUI takes a long time to show details of some entities

### ISSUE THREAD

**Issue by ZackHill05** [Senzing/senzing-api-server#97] opened 2019-10-03 14:32 UTC
When clicking on an entity to get more details in the GUI, it takes 40 seconds before the details come up. The screen is blank until the details come up, so to the user it looks like bringing up the details "didn't work".

When the details do come up, it takes another 40 seconds to show the relationships for this entity.

Two things:
1) It would be nice to have some indication that the GUI is still working on bringing up the information.
2) Does the database need to be tuned to make the detail display faster? Do indexes need to be added? I ask because for this one person it always takes this amount of time, but for most the details and relationships come back quickly. Another interesting thing about the relationships coming back so slowly for this one is only 4 relationships are returned. Getting details on another person with 4 relationships comes back quickly.

**Comment by docktermj** [comment] 2019-10-03 14:45
@arawinters Part of this is really a https://github.com/Senzing/entity-search-web-app issue.   When it comes to performance, I refer to @antaenc.

**Comment by docktermj** [comment] 2019-10-03 15:03
@ZackHill05 Would it be OK if I opened up a separate issue for your "thing #1" in the https://github.com/Senzing/entity-search-web-app repository?  (Or if you want to, that's OK with me)

**Comment by ZackHill05** [comment] 2019-10-03 15:06
Hi Michael,

Yes, please create a separate issue for #1.

Thanks!

Zachery Hill

**Comment by docktermj** [comment] 2019-10-03 15:10
New issue:  https://github.com/Senzing/entity-search-web-app/issues/69

**Comment by antaenc** [comment] 2019-10-03 19:19
Hi Zach,

Are you referring to the standard Senzing web components in a browser or the i2 integration? 
No, additional indexes are not required. 

The interesting comment is it only happens for one person and not others:

- Is the person this is slow for pulling back a different entity and relationships to other users where it is faster? 
- Are they in the office and on a more local network as opposed to being at home or travelling on a different slower network? 
- Anything else technically to explain why they might be slower? 

Ant

**Comment by barrycaceres** [comment] 2019-10-07 17:08
@ZackHill05 does the entity take a long time to display for the first one?  the first 8?  or for all of them?

I ask because there is some initialization that occurs on the first entity search.... and then there is some initialization for each thread (usually there are 8 threads for handling entity searches).  Trying to pin down what the cause might be.

**Comment by arawinters** [comment] 2019-10-08 15:07
@barrycaceres I left a comment on this issue on a different ticket. https://github.com/Senzing/entity-search-web-app/issues/67
It's a regression in the spinner behavior and is closely related to the graph api request. Though the regression only pertains to the spinner behavior and not the load time of the api request itself. what's happening is that the spinner is disapearing after the initial entity request, but before the graph api request is fullfilled, the time in between is the time spent waiting for the find network endpoint request.

**Comment by docktermj** [comment] 2019-11-14 14:09
@ZackHill05 Just checking in.  Did we resolve this to your satisfaction?

**Comment by ZackHill05** [comment] 2019-11-14 17:21
@docktermj not yet, but my team lead has asked me to make this my last priority with Senzing. If you need to close this issue, that's fine. I'll re-open when I have more time.

**Comment by docktermj** [comment] 2019-11-14 18:31
@ZackHill05 We'll keep it open so that we know it's an issue.   (cc: @barrycaceres )

**Comment by barrycaceres** [comment] 2020-05-14 17:04
I am pretty sure this is addressed in Senzing 1.15.2 with the performance improvements for obtaining entity networks.

**Comment by barrycaceres** [comment] 2020-05-14 17:05
Zack -- do you want me to close this issue, or would you like to upgrade to 1.15.2 and confirm first?

**Comment by ZackHill05** [comment] 2020-05-20 14:33
Hi Barry,

I’d like to confirm it first. We should be able to do so in our development environment. I’ll let you know what we find.

Thanks!

Zachery Hill

**Comment by barrycaceres** [comment] 2020-07-17 18:20
Zack -- any progress on this?  Did you get a chance to test the upgrade to v1.15.2?  Version 2.0.0 is being/has just been released this week (just an FYI).

**Comment by ZackHill05** [comment] 2020-07-17 18:23
Hi Barry,

Sorry for the late response. The customers say this no longer seems to be an issue, and I have 1.15.0 installed. Don’t know if 1.15.2 will give us even better performance.

Thanks!

Zachery Hill

**Comment by barrycaceres** [comment] 2020-08-04 20:29
Zach,

If it is no longer an issue, would you mind closing this issue?  If I don't hear back in two weeks, I can go ahead and close it.  Just trying to tidy things up on our open issues list.

Thanks!

-Barry

**Closed** 2020-09-22 17:21 UTC
Labels: performance
