### ISSUE TITLE
Spaces after a comma delimiter in CSV files causes incorrect parsing and incorrect data that is valid and loaded

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-api-server#265] opened 2022-02-08 01:24 UTC
When using the Web App to load a CSV file with a space after a delimiting comma, the data is incorrectly parsed. This results in valid data to load but isn't the data that is sent in to load. 

For example loading the following (note the space after the 3rd comma on the 2nd row) results in the results show in the image below.

```
DATA_SOURCE,RECORD_ID,NAME_FULL,ADDR_FULL, DATE_OF_BIRTH
TEST,1,"Anthony Cunningham", "787 Rotary Drive, Rotorville, Somewhere, 78777", 7/7/1977
```
Note:

- " before the address
- The remainder of the address is missing
- The second component in the address is pushed into the date of birth

![image](https://user-images.githubusercontent.com/28313221/152899997-6b0b415f-8a98-4f1a-94fe-9bf5b5cd6f83.png)

For additional details see: https://github.com/Senzing/compressedfile/issues/18

**Comment by barrycaceres** [comment] 2022-05-10 00:28
I have reproduced this issue with solely the API Server and `curl`.  I will debug it, but it is likely something in the Apache Commons CSV Parser (which we don't control).

**Comment by barrycaceres** [comment] 2022-05-10 17:29
I have opened a defect with the Apache Commons CSV team:

https://issues.apache.org/jira/browse/CSV-296

**Comment by barrycaceres** [comment] 2022-05-23 18:45
Does not look like the Apache team sees this as a bug.  Don't know if we can fix this.  I've been instructed that we should not spend a lot of resources trying to work around or fix this since the CSV is invalid.

**Comment by barrycaceres** [comment] 2022-08-01 12:48
Closing this issue as the Apache team has not addressed it and it does not look like they will

**Comment by barrycaceres** [comment] 2022-11-01 22:29
Apache Commons CSV version 1.9.0 has a means to address this issue.

**Closed** 2022-11-03 00:41 UTC
Labels: bug, triage
